@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for granting and validating a sidewalk permits type  on a commercial license - API Application

Container(mvc, "MVC", "C#, ASP", "A web application that provides user interface for the service provider.")
ContainerDb(db, " Database", "Relational Database Schema",  "Retrieve/Store licenses with request type sidewalk permit.")
Container_Ext(calculator, "Balady App Calculator Service", "C#", "A Service that Calculate Cost For Granting Commercial License")

Container_Boundary(api, "Commercial License API") {
    Component(controller, "SideWalkPermitController", "Spring Rest Controller", "Expose Apis to manage the license related to sidewalk(granting/renewal) permit type.")
    Component(sideWalkPermitService, "SideWalkPermitService", "Spring Service Bean", "Manage the logic of permits related to license commercial reqeust related to sidewalk permit type.")
    Component(calculatorRouterService, "CalculatorRouterService","Spring Service Bean", "Integrated with Balady App Calculator Service to calculate the fees related to the service.")
}
Rel(mvc, controller, "Uses", "JSON/HTTP")

Rel(sideWalkPermitService, db, "Uses", "TCP/IP")
Rel(controller, sideWalkPermitService, "Uses", "JSON/HTTP")
Rel(controller, calculatorRouterService, "Uses", "JSON/HTTP")
Rel(calculatorRouterService, calculator, "Uses", "JSON/HTTP")


@enduml