@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for granting and validating permits related to royal gaurd type - API Application

Container(mvc, "MVC", "C#, ASP", "A web application that provides user interface for the service provider.")
ContainerDb(db, " Database", "Relational Database Schema",  "Retrieve/Store commercial license related to license related to royal guard permit type.")

Container_Boundary(api, "Commercial License API") {
    Component(controller, "RoyalGuardPermitController", "Spring Rest Controller", "Expose Apis to manage the license related royal gaurd permit type.")
    Component(royalGuardPermitService, "RoyalGuardPermitService", "Spring Service Bean", "Manage the logic of permits related to royal gaurd.")
}

Rel(mvc, controller, "Uses", "JSON/HTTP")

Rel(royalGuardPermitService, db, "Uses", "TCP/IP")

Rel(controller, royalGuardPermitService, "Uses", "JSON/HTTP")

@enduml