@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for granting and validating permits related to vehicle parking type   - API Application

Container(mvc, "MVC", "C#, ASP", "A web application that provides user interface for the service provider.")
ContainerDb(db, " Database", "Relational Database Schema",  "Retrieve/Store rating related to license related to vehicle parking permit type.")

Container_Boundary(api, "Commercial License API") {
    Component(controller, "VehicleParkingPermitController", "Spring Rest Controller", "Expose Apis to manage the license related vehicle parking permit type.")
    Component(vehicleParkingPermitService, "VehicleParkingPermitService", "Spring Service Bean", "Manage the logic of permits related to vehicle parking.")
}
Container_Ext(commercialParkingZone, "Commercial Parking Zone", "C#, ASP", "A Service that Handles All Tasks Related to Parking Zones For vehicles(Retrieving , Validation)")

Rel(mvc, controller, "Uses", "JSON/HTTP")

Rel(vehicleParkingPermitService, db, "Uses", "TCP/IP")
Rel(vehicleParkingPermitService, commercialParkingZone, "Uses", "JSON/HTTP")

Rel(controller, vehicleParkingPermitService, "Uses", "JSON/HTTP")

@enduml