@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for creating and retrieving objection on a commercial license - API Application

Container(mvc, "MVC", "C#, ASP", "A web application that provides user interface for the service provider.")
ContainerDb(db, " Database", "Relational Database Schema",  "Retrieve/Store licenses with their related objections.")

Container_Boundary(api, "Commercial License API") {
    Component(controller, "ObjectionController", "Spring Rest Controller", "Expose Apis to manage the objection on a commercial license.")
    Component(objectionService, "ObjectionService", "Spring Service Bean", "Manage the logic of retrieving request and attach the objection to them.")
}
Rel(mvc, controller, "Uses", "JSON/HTTP")

Rel(objectionService, db, "Uses", "TCP/IP")
Rel(controller, objectionService, "Uses", "JSON/HTTP")


@enduml