@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for creating and retrieving objection on not belonging commercial license - API Application

Container(mvc, "MVC", "C#, ASP", "A web application that provides user interface for the service provider.")
ContainerDb(db, " Database", "Relational Database Schema",  "Retrieve/Store objection on not belonging to beneficiary commercial license.")

Container_Boundary(api, "Commercial License API") {
    Component(controller, "ObjectionLicenseNotBelongController", "Spring Rest Controller", "Expose Apis to manage the objection on commercial license not Belonging to beneficiary.")
    Component(objectionLicenseNotBelongService, "ObjectionLicenseNotBelongService", "Spring Service Bean", "Manage the logic of objection on commercial license not belonging to beneficiary .")
}

Rel(mvc, controller, "Uses", "JSON/HTTP")
Rel(objectionLicenseNotBelongService, db, "Uses", "TCP/IP")
Rel(controller, objectionLicenseNotBelongService, "Uses", "JSON/HTTP")

@enduml