@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for creating and retrieving objection on a Suspended commercial license - API Application

Container(mvc, "MVC", "C#, ASP", "A web application that provides user interface for the service provider.")
ContainerDb(db, " Database", "Relational Database Schema",  "Retrieve/Store suspended commercial licenses request with their objections.")
Container_Ext(calculator, "Balady App Calculator Service", "C#", "A Service that Calculate Cost For Granting Commercial License")

Container_Boundary(api, "Commercial License API") {
    Component(controller, "ObjectionOnHoldLicenseController", "Spring Rest Controller", "Expose Apis to manage the license related to objection on suspended commercial requests.")
    Component(objectionOnHoldLicenseService, "ObjectionOnHoldLicenseService", "Spring Service Bean", "Manage the logic of retrieving suspended commercial request and attach the objection to them.")
    Component(calculatorRouterService, "CalculatorRouterService","Spring Service Bean", "Integrated with Balady App Calculator Service to calculate the fees related to the service.")
}
Rel(mvc, controller, "Uses", "JSON/HTTP")

Rel(objectionOnHoldLicenseService, db, "Uses", "TCP/IP")
Rel(controller, objectionOnHoldLicenseService, "Uses", "JSON/HTTP")
Rel(controller, calculatorRouterService, "Uses", "JSON/HTTP")
Rel(calculatorRouterService, calculator, "Uses", "JSON/HTTP")

@enduml