@startuml Basic Sample
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

'Main Containers'
Person(Beneficiary, "Beneficiary")
System_Boundary(c1, "Balady Business Portal") {
Container(mvc, "MVC", "C#, ASP", "A web application that provides user interface for the service provider.")
Container(api, "Commercial Licence Api", "Java Spring", "Grant Commercial License For Business", $sprite="java")
Container(commonService, "Common Service", "Java Spring", "Common Functionality Among All Services", $sprite="java")
}

'Extension Component'
Container_Ext(sadad, "Sadad Api Gateway", "SoftwareService", "API Gateway For Payment")
Container_Ext(baladyBillsService, "Balady Bills Service", "Java, Spring", "Integrate With Sadad APi Gateway for Generating Bills",$sprite="java")
Container_Ext(calculator, "Balady App Calculator Service", "C#", "A Service that Calculate Cost For Granting Commercial License")
Container_Ext(boardContract, "Board Contract Service", "Java Spring", "A Service that Get Board Contract Owned By Beneficiary",$sprite="java")
Container_Ext(boardContractConfig, "Board Contract Configuration Service", "Java Spring", "A Service that  Get Zone Setting For Board and Requirements Related To Specific Isic Activity",$sprite="java")
Container_Ext(commercialQrApi, "Commercial Qr Service", "C#, ASP", "A Service that  Grant and Validate and  Cancel QR codes")
Container_Ext(commercialIssuingConsultation, "Commercial Issuing Consultation Service", "C#, ASP", "The CLA calls Commercial Issuing Consultation service via http to simulate the same procedure to produce a license without any fees to have an understanding about limitation.")
Container_Ext(craftService, "Craft Service", "Java , Spring", "A Service that  Craft Service for granting Craft Licence and Validate Crafts For Commercial License.",$sprite="java")
Container_Ext(engineeringOfficeApi, "Engineering Office Api", "Java , Spring", "A Service that  Get Engineering Office Details.",$sprite="java")
Container_Ext(gisService, "GIS Service", "C# , ASP", "A Service that  Get Gis Location details By Coordinates and Information About Zones",$sprite="java")
Container_Ext(sso, "SSO", "C#, ASP", "A Single sign-on System that handles authentication and authorization")
Container_Ext(commercialParkingZone, "Commercial Parking Zone", "C#, ASP", "A Service that Handles All Tasks Related to Parking Zones For vehicles(Retrieving , Validation)")
Container_Ext(activityManagementApi, "Activity Management Api", "Java, Spring", "A Service that  Manage the Activities Related to Granting Commercial License(Validate Activities Related To Salam Report and Meeting Civil Defense Rules)")
Container_Ext(blockedClientsApi, "Blocked Clients Api", "Java, Spring", "A Service that  Validate If The Client Is Blocked in the Municipality for the Provided Service.",$sprite="java")
Container_Ext(baladyServicesAPI, "Balady Services API", "Java", "A Service that  Validate And Retrieve Commercial Records For Commissioner.",$sprite="java")
Container_Ext(etmamintg, "Etmam Intg", "Java", "A Service that Validate and Aquire Orders For Balady Service And Get Order Details.",$sprite="java")
Container_Ext(selfSurveyApi, "Self Survey Api", "C#, ASP", "A Service that Get More Information About the License Rating.")
Container_Ext(integrationLayer, "Integration Layer", "IntegrationLayer(Apigee)", "A Service that Managing high value/volume of APIs with enterprise-grade security and dev engagement.")
Container_Ext(generalSecurity, "General Security", "External Service", "A Service that Get Approval For General Security.")
Container_Ext(ministryOfMunicipalAndRuralAffairsAndHousing, "Ministry of Municipal and Rural Affairs and Housing", "External Service", "A Service that  Get Information About Ejar Contracts and Status.")
Container_Ext(ministryOfCommerce, "Ministry Of Commerce", "External Service", "A Service that Get Information About Commercial Records , Commercial Record Applicant Relation ,Registration Ownership , Info About Blocked Families .")
Container_Ext(baladyInvestmentContract, "Balady Investment Contract(Foras)", "External Service", "Get Information About Investment Electronic Contracts.")
Container_Ext(classsificationPega, "Classification Pega", "External Service", "Get Information About Activities and Its Classifications And Special Activities that Require Special handling Like Furniture.")
Container_Ext(healthCertificateService, "Health Certificate Service", "External Service", "Get And Check health Certificates for Specific Users.")
Container_Ext(ministryOfLabor, "Ministry Of Labor", "External Service", "Get Labor Info Related To Employee.")
Container_Ext(salama, "Salama", "External Service", "Integrate with Civil Defense to Buy And Construct Salama Tools and Get Salama Report Number.")
Container_Ext(baladyBillsService, "Balady Bills Service", "External Service", "Grant/Cancel Special Permission For Business Openning in Crisis(Corona).")
Container_Ext(ministyOfJustice, "Ministry of Justice", "External Service", "Get Information About Deeds.")
Container_Ext(nationalInformationCenter, "National Information Center(Tawakkalna)", "External Service", "Get Information About Citizen.")
Container_Ext(moj, "Moj API", "External Service", "Provide Apis For Integration With Ministry Of Justice.")
Container_Ext(licenseSuspension, "License Suspension", "External Service", "Provide Apis For Integration With Ministry Of Justice.")

'Queue Component'
SystemQueue_Ext(messageBus, "Message Bus", "A message Broker that Enables Async Communication.")

'Beneficiary Relation'
Rel(Beneficiary, mvc, "Uses", "HTTP")

'SPA Relation'
Rel(mvc, api, "Calls", "HTTP")

'API Relations'
Rel(api, calculator, "Calls", "HTTP")
Rel(api, boardContract, "Calls", "HTTP")
Rel(api, commercialQrApi, "Calls", "HTTP")
Rel(api, commercialIssuingConsultation, "Calls", "HTTP")
Rel(api, craftService, "Calls", "HTTP")
Rel(api, engineeringOfficeApi, "Calls", "HTTP")
Rel(api, licenseSuspension, "Calls", "HTTP")

Rel(api, commonService, "Calls", "HTTP")
Rel(api, integrationLayer, "Calls", "HTTP")
Rel(api, gisService, "Calls", "HTTP")
Rel(api, commercialParkingZone, "Calls", "HTTP")
Rel(api, sso, "Calls", "HTTP")
Rel(api, etmamintg, "Calls", "HTTP")

Rel(api, selfSurveyApi, "Calls", "HTTP")
Rel(api, healthCertificateService, "Calls", "HTTP")
Rel(api, classsificationPega, "Calls", "HTTP")
Rel(api, blockedClientsApi, "Calls", "HTTP")
Rel(api, baladyServicesAPI, "Calls", "HTTP")
Rel(api ,messageBus , "Send Messages To ", "amqp")
Rel(api, activityManagementApi, "Calls", "HTTP")

'Common Service Relations'
Rel(commonService ,moj , "Calls", "HTTP")
Rel(commonService, baladyBillsService, "Calls", "HTTP")
Rel(commonService, integrationLayer, "Calls", "HTTP")

'Integration Layer Relations'
Rel(integrationLayer, ministryOfMunicipalAndRuralAffairsAndHousing, "Calls", "HTTP")
Rel(integrationLayer, generalSecurity, "Calls", "HTTP")
Rel(integrationLayer, ministryOfLabor, "Calls", "HTTP")
Rel(integrationLayer, ministyOfJustice, "Calls", "HTTP")
Rel(integrationLayer,moj , "Calls", "HTTP")
Rel(integrationLayer, baladyInvestmentContract, "Calls", "HTTP")
Rel(integrationLayer, salama, "Calls", "HTTP")
Rel(integrationLayer, ministryOfCommerce, "Calls", "HTTP")
Rel(integrationLayer, nationalInformationCenter, "Calls", "HTTP")

'Services Layer Relations'
Rel(baladyBillsService, sadad, "Calls", "HTTP")
Rel(boardContract, boardContractConfig, "Calls", "HTTP")

@enduml