@startuml Basic Sample
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

Person(Beneficiary, "Beneficiary")
System_Boundary(c1, "Balady Business Portal") {
Container(mvc, "MVC", "C#, ASP", "A web application that provides user interface for the service provider.")
Container(api, "Commercial Licence Api", "Java Spring", "Grant Commercial License For Business", $sprite="java")
}


Container_Ext(integrationLayer, "Integration Layer", "IntegrationLayer(Apigee)", "A Service that Managing high value/volume of APIs with enterprise-grade security and dev engagement.")
Container_Ext(gisService, "GIS Service", "C# , ASP", "A Service that  Get Gis Location details By Coordinates and Information About Zones",$sprite="java")
Container_Ext(commercialParkingZone, "Commercial Parking Zone", "C#, ASP", "A Service that Handles All Tasks Related to Parking Zones For vehicles(Retrieving , Validation)")
Container_Ext(etmamintg, "Etmam Intg", "Java", "A Service that Validate and Aquire Orders For Balady Service And Get Order Details.",$sprite="java")
Container_Ext(selfSurveyApi, "Self Survey Api", "C#, ASP", "A Service that Get More Information About the License Rating.")

Rel(Beneficiary, mvc, "Uses", "HTTP")
Rel(mvc, api, "Calls", "HTTP")
Rel(api, integrationLayer, "Calls", "HTTP")
Rel(api, gisService, "Calls", "HTTP")
Rel(api, commercialParkingZone, "Calls", "HTTP")
Rel(api, etmamintg, "Calls", "HTTP")
Rel(api, selfSurveyApi, "Calls", "HTTP")

@enduml